# List (Списки)
mutable (изменяемые)

Лекция 1

In [2]:
a = [1,2,3,4]
b = a[:] #слайс делает копию, иначе b просто будет вместо a
b += [5,6,7]

In [6]:
a

[1, 2, 3, 4, 0, 0, 0]

In [12]:
type(a)

list

In [13]:
a + a

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
a * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
a[0]

1

In [16]:
a[:2]

[1, 2]

In [21]:
a[2:]

[3, 4]

In [18]:
a[:]

[1, 2, 3, 4]

In [20]:
a[0:3:1] #идем от 0 индекса до 3 с шагом 1

[1, 2, 3]

In [8]:
a.append(333)
a

[1, 2, 3, 4, 0, 0, 0, 1, 333]

In [11]:
a.extend([2, 3, 4])
a

[1, 2, 3, 4, 0, 0, 0, 1, 333, 2, 3, 4]

# Tuple (кортеж)
Лекция 2 (35 мин - 1ч 14)


*можем лист в тупл перевести и наоборот*

In [125]:
a = ()
a

()

In [127]:
len(a)

0

In [19]:
a = (2, )
type(a) #В отличии от списка туплы нельзя изменять a[0] = 10 выдаст ошибку

tuple

In [128]:
type((1, 'one'))

tuple

In [18]:
a[0]

2

In [20]:
b = list(a) # Изменение тупла
b

[2]

In [21]:
b[0] = 10
a = tuple(b)
a 

(10,)

In [22]:
a = (1, 2, 3)

In [23]:
a[:2]

(1, 2)

In [26]:
(1, 2) + (2, 3) # конкатенация

(1, 2, 2, 3)

In [25]:
(1, 2) * 3

(1, 2, 1, 2, 1, 2)

In [36]:
a = (1, [2, 3, 4]) #лист можем вписать в кортеж 
a[1]

[2, 3, 4]

In [29]:
a[1].append(10) #записать что-то новое в кортеж не можем, но можем изменить лист
a

(1, [2, 3, 4, 10, 10])

In [34]:
c = ( 2, 3, 7)
c1, c2, c3 = c
c3

7

In [35]:
c = 2, 3, 7
type(c)

tuple

In [48]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

# Dictionary (Словарь)

In [37]:
d = {23: 37, 4: 5, 6: 23}
len(d)

3

In [40]:
d[23] # ищем по ключу

37

In [57]:
t = (2,4)
a = {'Tanya': {0:45}, 1.1: [{}], t: 'Misha'} #использовать разнородные признаки можно, но не надо. Лучше брать int или str. 

In [55]:
a[1.1]

[{}]

In [58]:
a[t]

'Misha'

In [44]:
a['Tanya']

{0: 45}

In [45]:
type(a)

dict

In [47]:
dir(dict) # все доступные методы  в словаре

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [59]:
list(a.keys())

['Tanya', 1.1, (2, 4)]

In [60]:
list(a.values())

[{0: 45}, [{}], 'Misha']

In [65]:
keys = list(a.keys()) # Ключ мы можем так поменять, а значение нет ( как я поняла, создалась копия, где мы поменяли)
keys[1] = 234
keys

['Tanya', 234, (2, 4)]

In [68]:
list(a.keys()) 

['Tanya', 1.1, (2, 4), 234]

In [69]:
id(keys)

2311615711040

In [74]:
id(list(a.keys())) #убедилась, что выше мы создали копию, так как id не совпал

2311614871360

In [71]:
a[234] = 1 # добавили в словарь
a

{'Tanya': {0: 45}, 1.1: [{}], (2, 4): 'Misha', 234: 1}

In [83]:
a.get('Tanya') #Отличие от [] в том, что, если обратимся к элементу, кот нет, то выведет None, а [] выдадут ошибку

{0: 45}

In [87]:
a.get('Tanya2' , 100) #мы можем сами задать, что он будет выводить, если значения такого нет


100

In [73]:
a[1.1] = 20 #Изменли значение по ключу
a

{'Tanya': {0: 45}, 1.1: 20, (2, 4): 'Misha', 234: 1}

In [76]:
del a[1.1]


KeyError: 1.1

In [77]:
a

{'Tanya': {0: 45}, (2, 4): 'Misha', 234: 1}

In [79]:
list(a.items())

[('Tanya', {0: 45}), ((2, 4), 'Misha'), (234, 1)]

In [80]:
p = dict() # создается пустой словарь
p = {}

In [81]:
p

{}

In [88]:
'Tanya' in a #Через in проверяем, есть ли такой ключ в словаре

True

In [89]:
'Tanya2' in a

False

In [91]:
'Tanya2' not in a #противоположно in

True

In [93]:
{'1': 1, '4': 5} | {'1' : 3 ,'2' : 2} #с помощью | можно объединить словари

{'1': 3, '4': 5, '2': 2}

# Sets (Множества)

Хранит только уникальные значения, которые нельзя изменить

In [97]:
a = set()
a = {1, 2, 'a', 4.2}
a

{1, 2, 4.2, 'a'}

In [129]:
type({"a", 1})

set

In [100]:
set([1, 2, 3, 3, 0]) #2 тройки соединились в 1 уникальную тройку

{0, 1, 2, 3}

In [101]:
len(a)

4

In [104]:
a.add(-1) #порядок при выводе мб любой
a

{-1, 1, 2, 4.2, 'a'}

In [105]:
b = {2, 3, 4}

In [106]:
a | b #Объединение

{-1, 1, 2, 3, 4, 4.2, 'a'}

In [107]:
a & b #пересечение

{2}

In [108]:
a.difference(b) #отличие а от б

{-1, 1, 4.2, 'a'}

In [110]:
a - b #аналогично выше (удали из а все, что есть в б )

{-1, 1, 4.2, 'a'}

In [111]:
1 in a

True

In [113]:
3 not in a

True

In [114]:
a = {1, 2, 3}
b = {3, 4, 5}
a.union(b)

{1, 2, 3, 4, 5}

# Conditions (операторы)

Условные операторы (If, else)

In [118]:
a = 1

if a > 2:
    print(a)
else: 
    print(a + 3)

4


In [120]:
a = 1 # после pass прекращается работа

if a > 2:
    print(a)
elif a < 2: 
    pass
else: 
    print(a + 100)

In [121]:
"a" + "aaa" if (a + 2 < 5) else "bbb"

'aaaa'

# Loops (Циклы)

In [128]:
for i in range(2, 10, 3): #цикл от 2 до 10 с шагом 3
    print(i)


2
5
8


In [130]:
n = 5
for i in range(n):
    print(i)

0
1
2
3
4


In [133]:
a = [1,2,3, 'a']
for x in a:
    print(x)

1
2
3
a


In [135]:
a = {1, 0, -10, 1}
for x in a:
    print(x)

0
1
-10


In [136]:
a = {1: 1, 2: 0, 15: -10, 16: 1} #в словарях он перебирает только ключи
for x in a:
    print(x)

1
2
15
16


In [137]:
a = {1: 1, 2: 0, 15: -10, 16: 1}
for x in a:
    print(x, a[x])

1 1
2 0
15 -10
16 1


In [140]:
a = {1: 1, 2: 0, 15: -10, 16: 1}
for x in a.items():
    print(x)

(1, 1)
(2, 0)
(15, -10)
(16, 1)


In [141]:
a = {1: 1, 2: 0, 15: -10, 16: 1}
for key, value in a.items():
    print(key, value)

1 1
2 0
15 -10
16 1


In [142]:
a = (1, 0, -10, 1)
for x in a:
    print(x)

1
0
-10
1


In [143]:
for x in 1, 0, -10, 1:
    print(x)

1
0
-10
1


In [147]:
import random
n = 10
a = [0] * n
for i in range(n):
    a[i] = random.randrange(10)
a.sort()


[0, 0, 1, 2, 3, 3, 3, 5, 6, 7]

In [148]:
l = 0
r = n
x = 6
while r - l > 1:
    m = (r + l) // 2
    if a[m] > x:
        r = m
    else: 
        l = m
        
print(l, r, x, a[l])

8 9 6 6


In [152]:
for i in range(10):
    if i < 5:
        continue
    print(i)

5
6
7
8
9


In [153]:
for i in range(10):
    if i < 5:
        continue
    print(i)
else:
    print("abc")

5
6
7
8
9
abc


In [3]:
for i in range(10):
    if i >= 5:
        print(i)
else:
    print("abc")

5
6
7
8
9
abc


In [155]:
for i in range(10):
    if i < 5:
        break
    print(i)
print("abc")

abc


In [4]:
a = [1, 2, 3, 1]

In [5]:
a.index(1)

0

In [7]:
a. index(1, 1) #то есть мы ищем в каком индексе у нас 1, начиная с шагом +1, то есть 2 - индекс 0, 3 - индекс 1, 1 - индекс 3


3

In [8]:
range(10)

range(0, 10)

# Modules (Модули)

In [9]:
import random
import random as rn

In [10]:
type(rn)

module

In [11]:
rn.randrange(10)

8

In [13]:
from random import randrange
randrange(10)

7

# Closures (вложенные функции)


In [5]:
def r():
    def g(x):
        return 1
    def f(x):
        return g(x)
    print(f(10))
print (r())

1
None


In [12]:
def f():
    y = 4
    def g(x): 
        print(y * 2)
        return y
    g(2)
    return g
w = f()
w(2)

8
8


4

In [25]:
def my_func():
    u = 1
    def inner_func():
        nonlocal u
        print(u)
        u = u + 2
    return inner_func
a = my_func()

a()
a()

1
3


# Function Fabric
(2:04)

In [2]:
def mul(x, y):
    return x * y
print(mul(2, 5))

10


In [3]:
def make_mul(y):
    def mul(x):
        return x * y
    return mul


In [5]:
mul5 = make_mul(5)
print(mul5(9))

45


In [8]:
make_mul.__name__

'make_mul'

In [10]:
dir(make_mul)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

# String (строки)

In [54]:
s = "1, 2, 34, 4, 56, 8"
s1 = 'три четыре'

In [60]:
print(s)
print(s1)

1, 2, 34, 4, 56, 8
три четыре


In [30]:
a = s.split()
a

['один,', 'два,', ',', '4', '8']

In [64]:
s.split(": ") # непонятно


['1, 2, 34, 4, 56, 8']

In [39]:
a = ['1', 'a', '3']
"$".join(a)

'1$a$3'

In [61]:
s[1:7:1]


', 2, 3'

In [62]:
a = list(s)

In [67]:
a[1] = '5'
a

['1',
 '5',
 ' ',
 '2',
 ',',
 ' ',
 '3',
 '4',
 ',',
 ' ',
 '4',
 ',',
 ' ',
 '5',
 '6',
 ',',
 ' ',
 '8']

In [68]:
t = ''.join(a)
t

'15 2, 34, 4, 56, 8'

In [69]:
for c in s:
    print(c)

1
,
 
2
,
 
3
4
,
 
4
,
 
5
6
,
 
8


In [71]:
len(s)

18

In [89]:
import time
for i, c in enumerate(s):
    print(i, c)
print(time.time())

0 1
1 ,
2  
3 2
4 ,
5  
6 3
7 4
8 ,
9  
10 4
11 ,
12  
13 5
14 6
15 ,
16  
17 8
1667215588.8718426


In [90]:
for i in range(len(s)):
    print(i, s[i])
print(time.time())

0 1
1 ,
2  
3 2
4 ,
5  
6 3
7 4
8 ,
9  
10 4
11 ,
12  
13 5
14 6
15 ,
16  
17 8
1667215593.0294867


In [91]:
s * 2

'1, 2, 34, 4, 56, 81, 2, 34, 4, 56, 8'

In [95]:
s + '2'

'1, 2, 34, 4, 56, 82'

# Format string

In [96]:
'The sum 1 + 2 is {0}'.format(1+2)

'The sum 1 + 2 is 3'

In [102]:
num = 10
"%d < %aaaa" % (num, 15)

'10 < 15aaa'

In [106]:

"%(num)d < %(num2)a" % {'num' : 12, 'num2' : 15}

'12 < 15'

In [109]:
'The sum 1 + 2 is {0} < {1}'.format(1+2, 4)

'The sum 1 + 2 is 3 < 4'

In [110]:
'res = {res}, cnt = {cnt}'.format(res = 4, cnt = 3)

'res = 4, cnt = 3'

In [114]:
cnt = 10
res = 5
f"cnt = {cnt:05d}" #выравнивание нулями до 5 символов

'cnt = 00010'

# Class

In [13]:
class A:
    """
    This class do nothing
    """
    pass
dir(A)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [3]:
A.__doc__

'\n    This class do nothing\n    '

In [4]:
help(A)

Help on class A in module __main__:

class A(builtins.object)
 |  This class do nothing
 |  
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [9]:
AA = A
AA == A

True

In [11]:
1 == 1

True

In [36]:
class A:
    def __init__ (self):
        self.a = '123'
        self.b = 10 ** 10
        self.c = 15
        self._d = 237 #считается приватной в мире питона
    def say(self):
        self.compute()
        print(self.b + self.c)
    def compute(self):
        self.b += 3
        print(self.b)
A()

In [37]:
ex = A()
ex.a, ex.b, ex.c, ex._d

('123', 10000000000, 15, 237)

In [21]:
ex.say()

10000000018


In [26]:
ex.compute()

10000000003


In [31]:
ex.a = '234'
ex.b += 500

In [33]:
ex.a

'234'

In [34]:
ex.b

10000000500

In [38]:
A.say(ex)

10000000003
10000000018


In [39]:
type(ex)

__main__.A

In [40]:
type(ex) == A

True

1:19 (18.10)

In [1]:
class B:
    bananas = 3
    @staticmethod
    def go(): #можно вызывать без создания экземпляра класса
        print('Res go', B.bananas)
        
    def say(self):
        print('self bananas', self.bananas)
        print('B.bananas', B.bananas)
    def __init__(self):
        self.a = 123

In [2]:
B().say()

self bananas 3
B.bananas 3


In [3]:
B()

In [4]:
B().a

123

In [5]:
b1 = B()
b1.bananas += 1
b1.bananas, B.bananas

(4, 3)

In [6]:
b1.say()

self bananas 4
B.bananas 3


In [9]:
class A(B):
    qqq = 123456
    def __init__(self, high, wide = 1.4):
        super().__init__() #инициализация от B
        self.a = 1
        self.wide = wide
        self._high = high
    def say(self):
        super().go()
        print('Hello!')
        self._say
    def _say(self):
        print('Buy!')
    def run(self):
        print('RUN {:010d} {} {} '.format(self.a, self.wide, self.high))
    def __say(self): #2 подчеркивания значит, что нельзя наследовать, нельзя вне брать
        print('Max secret')
    def __str__(self):
        return 'I am' + str(self.a)

In [12]:
a = A(10)
a.say()

Res go 3
Hello!


In [13]:
a._high

10

In [14]:
a.wide

1.4

In [15]:
a._say()

Buy!


In [18]:
a.__str__()

'I am1'

In [20]:
a._A__say() #просто a.__say вызовет ошибку

Max secret


In [23]:
x = [1, 2, 3]
y = x

id(x) == id(y)

True

In [25]:
x.append(1)
print(x)
print(y)

[1, 2, 3, 1]
[1, 2, 3, 1]


In [26]:
id(x) == id(y)

True

In [27]:
y.append(1)
print(x)
print(y)
id(x) == id(y)

[1, 2, 3, 1, 1]
[1, 2, 3, 1, 1]


True

In [28]:
x = [1, 2, 3]
y = x.copy
id(x) == id(y)

False

# Декораторы
2:39 (18.10)


In [14]:
def my_decorator(func):
    def new_funk(*args, **kwargs):
        print('Start ' + func.__name__)
        print(' args ', args) #позиционные аргументы функции
        print(' kwargs ', kwargs)
        res = func(*args, **kwargs)
        print('Finish ' + func.__name__ + ' Result ' + str(res))
        return res
    return new_funk


In [15]:
@my_decorator
def funk1(a, b, c = 5 ):
    return a * b + c

In [18]:
print(funk1(1,2, c = 0))

Start funk1
 args  (1, 2)
 kwargs  {'c': 0}
Finish funk1 Result 2
2


In [23]:
a = my_decorator(funk1)
a(1, 2)

Start new_funk
 args  (1, 2)
 kwargs  {}
Start funk1
 args  (1, 2)
 kwargs  {}
Finish funk1 Result 7
Finish new_funk Result 7


7

In [34]:
def funk2(a, b, c = 1 ):
    return a + b + c
funk2(1,3)

5

# Pack/ Unpack

In [35]:
a, b, c = (1, 2, 3)
print(a, b, c)

1 2 3


In [36]:
a = list(range(15))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [37]:
c, d, *e, f = a
print(c)
print(d)
print(*e)
print(f)

0
1
2 3 4 5 6 7 8 9 10 11 12 13
14


In [40]:
def func(a, b, c):
    print(a, b, c)
    return a + b

d = {'c' : 'Tanya'}
func(1, b = 3, **d)

1 3 Tanya


4

In [41]:
print(*['a', 'b', 3])

a b 3


In [42]:
print(['a', 'b', 3])

['a', 'b', 3]


Лекция 25.10

# Property
44:00


In [3]:
class Table:
    def __init__(self):
        self._color = '#000000'
    
    def get_color(self):
        return self._color
    
    def set_color(self, color):
        if len(color) != 7:
            print('color != 7')
            raise ValueError
        self._color = color

In [51]:
table = Table()
print(table.get_color())
table.set_color('#FFFFFF')
print(table.get_color())


#000000
#FFFFFF


In [52]:
table.set_color('#FFFFFFF')
print(table.get_color())

color != 7


ValueError: 

In [4]:
class Table:
    def __init__(self):
        self._color = '#000000'
    
    @property
    def color(self):
        return self._color
    
    @color.setter
    def color(self, color):
        if len(color) != 7:
            print('color != 7')
            raise ValueError
        self._color = color 
    

In [9]:
table = Table()
print(table.color)
table.color = '#FFFFFF'
print(table.color)

#000000
#FFFFFF


# Iterators
Знаем текущее состояние, знаем следующее состояние


In [20]:
class MyIterator:
    def __init__(self, n):
        self.n = n
        pass
    def __iter__(self): #готовит объект к началу операции
        self.element_id = self.n
        return self
    def __next__(self):
        if self.element_id == 0:
            raise StopIteration
        else:
            cur = self.element_id
            self.element_id -= 1
            return cur, cur * cur, cur ** 3

In [3]:
it = MyIterator(10)
it = iter(it)
for i in it:
     print(i)

(10, 100, 1000)
(9, 81, 729)
(8, 64, 512)
(7, 49, 343)
(6, 36, 216)
(5, 25, 125)
(4, 16, 64)
(3, 9, 27)
(2, 4, 8)
(1, 1, 1)


In [5]:
it = MyIterator(10)
it = iter(it)
i, j, k = next(it)
print(i, j, k)
i, j, k = next(it)
print(i, j, k)

10 100 1000
9 81 729


In [14]:
it = MyIterator(10)
it = iter(it)
for i in range(9):
    print(next(it))

(10, 100, 1000)
(9, 81, 729)
(8, 64, 512)
(7, 49, 343)
(6, 36, 216)
(5, 25, 125)
(4, 16, 64)
(3, 9, 27)
(2, 4, 8)


In [28]:
it = MyIterator(10)
for i in it:
    print(next(it))

(9, 81, 729)
(7, 49, 343)
(5, 25, 125)
(3, 9, 27)
(1, 1, 1)


# Generator
(1:27)

In [2]:
def my_gen1(): #плохо тем, что выделяем память под все элементы, было бы удобнее хранить только текущее состояние
    n = 10
    i = n
    a = []
    while i > 0:
        a.append(i)
        i -= 1
    return a


In [3]:
def my_gen2():
    i = 10
    while i > 0:
        yield i # возвращаем текущее значение
        i -= 1
        

In [7]:
it = my_gen2()
print(next(it))
print(next(it))
print(next(it))
it = my_gen2()
print(next(it))

10
9
8
10


In [8]:
for i in my_gen2():
    print(i)

10
9
8
7
6
5
4
3
2
1


# Lambda

In [13]:
def f(x, y):
    return 2 * x + 1 + y

g = lambda x, y: 2 * x + 1 + y

In [10]:
a = f(1, 2)
a

5

In [14]:
b = g(1, 2)
b

5

# Iterator / Generator Examples
### map

In [22]:
a = map(lambda x: x ** 2, [1, 2, 3, 4])
a

In [23]:
it = iter(a)
print(next(it))
print(next(it))
print(next(it))

1
4
9


In [26]:
a = map(lambda x: x ** 2, [1, 2, 3, 4])
for x in a:
    print(x)

1
4
9
16


In [27]:
list(map(lambda x: x ** 2, [1, 2, 3, 4]))

[1, 4, 9, 16]

In [31]:
a = map(lambda x: x ** 2, map(int, ['1', '2', '3']))
for x in a:
    print(x, type(x))

1 <class 'int'>
4 <class 'int'>
9 <class 'int'>


### range

In [44]:
it = range(10)
it = iter(it)
for i in it:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [45]:
list(map(lambda x: x ** 2, range(5)))

[0, 1, 4, 9, 16]

### filter

In [2]:
list(filter(lambda x: x % 2 == 0, range(10)))

[0, 2, 4, 6, 8]

### zip

In [52]:
list(zip(range(5), [1, 3, 5, 2]))

[(0, 1), (1, 3), (2, 5), (3, 2)]

In [55]:
list(zip(('a', 'b', 'c', 'd'), range(5), [1, 3, 5, 2]))

[('a', 0, 1), ('b', 1, 3), ('c', 2, 5), ('d', 3, 2)]

### enumerate

In [1]:
list(enumerate([32, 52, 36, 44]))

[(0, 32), (1, 52), (2, 36), (3, 44)]

# Itertools

In [3]:
import itertools
for c in itertools.count(10):
    if c % 174 == 13:
        break
    else:
        print(c)

10
11
12


In [4]:
for c in itertools.repeat('a', 3):
    print(c)

a
a
a


In [5]:
for c in itertools.accumulate([1, 2, 3, 4, 5]):
    print(c)

1
3
6
10
15


In [6]:
for c in itertools.chain('ABCD', 'Tanya'):
    print(c)

A
B
C
D
T
a
n
y
a


In [14]:
[(c, list(v)) for c, v in itertools.groupby('AAABBBBBBCDDD')]

[('A', ['A', 'A', 'A']),
 ('B', ['B', 'B', 'B', 'B', 'B', 'B']),
 ('C', ['C']),
 ('D', ['D', 'D', 'D'])]

In [20]:
a = itertools.groupby('AAABBBBBBCAADDDAA', 
                     lambda x: {'A' : 1, 'B' : 2, 'C' : 3, 'D' : 1 }[x])
[(c, list(v)) for c, v in a]

[(1, ['A', 'A', 'A']),
 (2, ['B', 'B', 'B', 'B', 'B', 'B']),
 (3, ['C']),
 (1, ['A', 'A', 'D', 'D', 'D', 'A', 'A'])]

In [23]:
list(itertools.zip_longest(range(5), [1, 3, 5, 2], fillvalue = 'abc'))

[(0, 1), (1, 3), (2, 5), (3, 2), (4, 'abc')]

In [11]:
list(filter(lambda x: x % 3 != 0, range(1,11)))

[1, 2, 4, 5, 7, 8, 10]

Короткий генератор

In [1]:
gen = (i for i in range(10))
gen

<generator object <genexpr> at 0x000001EC26A8CF90>

In [2]:
next(gen)

0

In [3]:
next(gen)

1

In [6]:
for x in gen:
    print(x)

2
3
4
5
6
7
8
9


In [7]:
gen = (i * i for i in range(10) if i % 2 == 0)
for x in gen:
    print(x)

0
4
16
36
64


In [8]:
gen = (i * i + j for i in range(10) if i % 2 == 0 for j in range(5))
for x in gen:
    print(x)

0
1
2
3
4
4
5
6
7
8
16
17
18
19
20
36
37
38
39
40
64
65
66
67
68


In [9]:
a = [i * i + j for i in range(10) if i % 2 == 0 for j in range(5)]
a

[0,
 1,
 2,
 3,
 4,
 4,
 5,
 6,
 7,
 8,
 16,
 17,
 18,
 19,
 20,
 36,
 37,
 38,
 39,
 40,
 64,
 65,
 66,
 67,
 68]

In [11]:
d = {i: i * i  for i in range(10) if i % 2 == 0 }
d

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

In [14]:
s = { i % 3  for i in range(10) }
s

{0, 1, 2}

In [15]:
k = 0
a = [k:= k + i for i in range(10)]
a

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]

# Метаклассы
классы, экземпляры которых сами являются классами

In [16]:
class A:
    x = 10
    def __init__(self, x):
        self.x = x
    def say(self):
        print('Hello')
    pass

In [18]:
type(A)

type

In [23]:
B = type('Ba', (), {'x' : 10, 'say' : lambda self: print('Hello', self.x) })

In [24]:
type(B)

type

In [25]:
ex = B()
ex.say()

Hello 10


In [26]:
type(ex)

__main__.Ba

In [27]:
import time
class InvocationLoggerMetaClass(type):
     def __new__(cls, classname, parents, attributes):
        new_attributes = {}
        for key, attr in attributes.items():
            if callable(attr):
                def make_logger(key, attr):
                    def logger(*args, **kwargs):
                        print('Start method', key)
                        be = time.time()
                        res = attr(*args, **kwargs)
                        en = time.time()
                        print('Finish', key, 'Time', en - be)
                    return logger
                attr = make_logger(key, attr)
            new_attributes[key] = attr
            
            
        return super().__new__(cls, classname, parents, new_attributes)

In [28]:
class Account(object, metaclass = InvocationLoggerMetaClass):
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
    def compute_sum(self):    
        return self.x + self.y + self.z
    def compute_mul(self):
        return self.x * self.y * self.z
    def compute_max(self):
        return max(self.x, self.y, self.z)

In [29]:
acc = Account(1, 2, 3)
acc.compute_sum()

Start method __init__
Finish __init__ Time 0.0
Start method compute_sum
Finish compute_sum Time 0.0


# Files

In [2]:
file = open("EX.tsv", encoding = 'utf-8')
for line in file:
    print(line)
file.close()

Лютова Татьяна самая лучшая

Михаил Ионов тутутур

2321



In [3]:
file = open("EX.tsv", encoding = 'utf-8')
line = file.readlines()
file.close()
line

['Лютова Татьяна самая лучшая\n', 'Михаил Ионов тутутур\n', '2321\n']

In [8]:
with open("EX.tsv", encoding = 'utf-8') as f: #можно не закрывать 
    print(f.readline())

Лютова Татьяна самая лучшая



# Библиотеки

In [1]:
import numpy as np
a = np.ones((10, 14), dtype = np.int32) # ones  создает матрицу 10 строк, 14 столбцов, заполняет единицами

In [2]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
b = np.array([[1, 2], [3, 4]])

In [7]:
b

array([[1, 2],
       [3, 4]])

In [8]:
b = np.array([[1, 2, 3], [3, 4]], dtype = object)

In [9]:
b


array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [10]:
print(b[0])

[1, 2, 3]


In [13]:
print(b[0][0])

1


In [16]:
for x in b:
    print(x)
    print('X end')
    for y in x:
        print(y)

[1, 2, 3]
X end
1
2
3
[3, 4]
X end
3
4


In [6]:
b = a[1:10, 1].copy()
print(b, 'First b')
b[0] = 18
print(a, 'End a')
print(b)

[1 1 1 1 1 1 1 1 1] First b
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]] End a
[18  1  1  1  1  1  1  1  1]


In [7]:
c = ...
c

Ellipsis

In [15]:
a = np.array([[2, 3, 4], [1, 7, 9]])
b = np.array([[1, 4, 5], [6, 7, 8]])

In [11]:
a.shape

(2, 3)

In [12]:
a.shape == b.shape

True

In [16]:
a%b

array([[0, 3, 4],
       [1, 0, 1]], dtype=int32)

In [17]:
c = (a + b) * (a - b)
c

array([[  3,  -7,  -9],
       [-35,   0,  17]])

In [18]:
a

array([[2, 3, 4],
       [1, 7, 9]])

In [23]:
print(np.array([[10], [10]]))

[[10]
 [10]]


In [24]:
a < np.array([[10], [10]])

array([[ True,  True,  True],
       [ True,  True,  True]])

In [25]:
b


array([[1, 4, 5],
       [6, 7, 8]])

In [26]:
np.logical_and(a < 8, b > 2)

array([[False,  True,  True],
       [ True,  True, False]])

In [28]:
mask = ((a < 10) & (b < 5)) | (a > 4)
print(a)
print(mask)
print(a[mask])

[[2 3 4]
 [1 7 9]]
[[ True  True False]
 [False  True  True]]
[2 3 7 9]


In [29]:
a[mask] = 10
a

array([[10, 10,  4],
       [ 1, 10, 10]])

In [32]:
a[mask] = [10, 20, 30, 40]
a

array([[10, 20,  4],
       [ 1, 30, 40]])

In [35]:
c = np.array([1, 2, 3, 4, 5])
ids = np.array([1, 2])
print(c[ids])

[2 3]


In [36]:
c[ids] = 0
c

[1 0 0 4 5]


In [37]:
c = np.array([1, 2, 3, 4, 5])

In [39]:
c[[1,2]] = 0
c

array([1, 0, 0, 4, 5])